### ISSUE TITLE
Support 256 colors

### ISSUE THREAD

**Issue by secrettriangle** [chjj/blessed#108]

**Comment by chjj** [comment]
@secrettriangle, blessed has almost always supported 256 colors. For example, `bg: 131` and `bg: '#a12f01'` are perfectly acceptable values. However, if your terminal doesn't support 256 colors, blessed will "reduce" the colors to 0-1, 0-7, or 0-15 in [the smartest way it can][1]. See [lib/colors.js][2].

If someone is having trouble with this, they might not be using a 256 color terminfo. Maybe they're using `xterm` instead of `xterm-256color`. We could try adding a Screen option to override the terminfo check (as the user might really be using a 256 color terminal), but it could break some non-256color terminals.

[1]: https://github.com/chjj/blessed/blob/master/lib/widget.js#L1175
[2]: https://github.com/chjj/blessed/blob/master/lib/colors.js

**Comment by secrettriangle** [comment]
Aha! I see `{#a12f01}hello world{/#a12f01}` works too. Is this documented somewhere?

**Comment by chjj** [comment]
Probably not. There's a few implicit features like that which aren't documented.
