### ISSUE TITLE
unicode content in windows

### ISSUE THREAD

**Issue by yaronn** [chjj/blessed#130]
The following program prints a box with braille content:

    var blessed = require('blessed');
    var screen = blessed.screen();
    var box = blessed.box({
        border: {
            type: 'line'
        },
        width: "10%",
        height: "10%",
        content: String.fromCharCode(0x2812)
    });
    screen.append(box);
    screen.render();

I run it on windows 7 default terminal (after configuring a special unicode font) and get this:

![image](https://cloud.githubusercontent.com/assets/1359037/7304656/7d318f36-ea01-11e4-9bf0-6894c7671ffd.png)

It can be hard to see but the box content is actually printed correctly (the two dots after the B in the middle) only the border is incorrect. 

Next I set:

    $> SET TERM=windows-ansi

and get:

![image](https://cloud.githubusercontent.com/assets/1359037/7304687/b3e7926e-ea01-11e4-800e-144fa4f2c4a7.png)

So here the border is correct and the unicode box content is not.

Then I change in blessed/tput.js Tput.prototype.detectUnicode to always return true and I get the expected output:

![image](https://cloud.githubusercontent.com/assets/1359037/7304724/d5acc1bc-ea01-11e4-9d8b-81d097bbebfe.png)

(actually the border has a curve but not critical)

So it seems that detectUnicode is not working correctly on widnows (though I'm not sure how to fix it - environment variables in windows will not convey this information). Regardless I'm curious why the unicode worked before setting the terminal to ANSI.

**Comment by chjj** [comment]
Hmmm, yeah, I'm guessing windows doesn't have the proper locale env variables.

This raises another question too. The first time you ran it, it tried to use ACS. For some reason blessed thought ACS was supported.

@yaronn, are there any env variables on windows that suggest whether unicode is supported or not? Otherwise, I'll have to do some research. Since windows is pretty standard compared to the myriad terminals on unix, we could just assume windows supports unicode I guess.

**Comment by chjj** [comment]
Also, that curve in the ACS characters is most likely due to the font or cell behavior. Whatever font iTerm2 uses (or how it spaces cells vertically) also effects ACS negatively.

**Comment by chjj** [comment]
@yaronn, maybe you can clear some of this up. You probably know more than I do.

After some stackoverflowing, it looks like [codepage 866](https://en.wikipedia.org/wiki/Codepage_866) is the default in the windows console.

In order to use unicode, you need to run `chcp 65001` (change to codepage 65001/utf-8). Also, the Lucida console font is also necessary to display everything properly as far as I can tell.

Some people just add `/K chcp 65001` to their cmd.exe shortcut, or change the codepage in the windows registry, so they're always using utf-8. Is there anyway to check the codepage for the console in windows?

One thing we know for sure is that ACS is not supported (or windows-ansi says it's supported, but it isn't in reality which would mean we should set it as `broken`).

So `brokenACS = true;` and `unicode = isCodepage65001();` I guess.

Sources:

- http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how
- http://stackoverflow.com/questions/19955385/utf-8-in-windows-7-cmd
- http://stackoverflow.com/questions/14109024/how-to-make-unicode-charset-in-cmd-exe-by-default
- http://stackoverflow.com/questions/1035388/unicode-output-on-windows-command-line

**Comment by chjj** [comment]
@yaronn, the reason the utf-8 char worked before switching to windows-ansi may have been because U8 was 1 in the terminfo. So I'll try to explain what happened in each instance:

Your first try (not windows-ansi): whatever TERM and terminfo you were using supported ACS, and also probably supported U8 (which can be a fallback for detectUnicode if there is no locale env variable). Since blessed always tries to use ACS, even if unicode is available, it tried to do ACS which gave you Qs and Ks. So, the configuration: `unicode = detectUnicode() || U8`, `U8 = true`, `detectUnicode() = false`, `acs = true`.

Your second try: you switch to windows-ansi, which correctly says ACS is not supported. So: `unicode = detectUnicode() || U8`, `U8 = false`, `detectUnicode() = false`, `acs = false`.

Your third try: you used a terminfo (windows-ansi?) which did not support ACS, and you forced blessed to use unicode. `unicode = detectUnicode() || U8`, `U8 = false`, `detectUnicode() = true`, `ACS = false`. Which is correct.

One thing we could do, is change the windows-ansi terminfo we ship and set U8 to true.

**Comment by chjj** [comment]
@mscdex, what do you think of setting `U8` (utf-8) to `1` by default in the windows-ansi terminfo we ship?

We could also just check for windows in blessed.

**Comment by chjj** [comment]
It looks like we would have to make a call to `GetConsoleCP()` to check for CP 65001: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683162(v=vs.85).aspx

Not easy, short of a C++ binding (and blessed really shouldn't have to be compiled).

**Comment by mgliewe** [comment]
offtopic: while listening, i noticed that assumed/supposed ACS support on various terminals seems to be a common issue.. 
Tell me if im wrong, as far as i unterstand, ACS ist mostly used for frame decoration on 'thumb' terminals.
Nowerdays, where UTF and locales/codepages are common on most terminals, wouldn't it be wise to drop support for that feature all together?
(i'm aware of the fact that lots of the confusion comes from terminfo, resp the lack of or the wrong one..)

**Comment by mscdex** [comment]
@chjj IIRC the last time I tried using cp65001 with the standard Windows command prompt, things started to break (at least on Windows 7), so I would be careful about using it. Also, you'd also have to make sure that the current console font supports utf8 characters, so AFAIK that means having to use a truetype font instead of the default raster font.

**Comment by mscdex** [comment]
Additionally, you can get the current code page by calling out to `chcp` without any arguments.

**Comment by chjj** [comment]
@mscdex, that's good. We could call `chcp` with spawnSync, but unfortunately spawnSync is only on later versions of node, and waiting to render the screen while waiting for an async call to return might be awkward. I suppose we could just recommend that windows users use the latest node. You're right about the font. People were recommending use of the Lucida console font.

@mgliewe, what do you mean it's a "common" issue? It's an issue here because the windows console was used with the wrong terminfo. There are still situations where ACS is useful (someone doesn't have a unicode locale setup, but they do have an ACS terminal). 

I don't want blessed to deviate from ncurses too much in terms of compat. ncurses still does the same thing for ACS.

**Comment by chjj** [comment]
That commit is untested.

**Comment by chjj** [comment]
@yaronn, try the latest commit with TERM=windows-ansi and see what happens.

**Comment by chjj** [comment]
Just fixed the CCP check implementation a bit. Apparently it's chcp.com instead of chcp.exe, and the output is something like `Active code page: 000\n\n` instead of just a number like I thought originally. Also, apparently the default code page is 437: https://en.wikipedia.org/wiki/Code_page_437

**Comment by chjj** [comment]
Testing the latest blessed commit now on windows console. The strange thing is, if the code page is 437 everything works as it should. If I change the code page to cp65001, I get: `Error: This socket is closed.` when the execFileSync call runs. It has something to do with the stdout FD. If I set stdout to `pipe`, I guess this error. If I set it to `ignore` or `inherit` or `-1`, everything is fine, but obviously the output no longer works.

Any windows node.js experts here?

**Comment by chjj** [comment]
Oh, I see what's happening. For some reason the windows child process is closing the stdout FD of its parent/blessed process even if stdio is `pipe`. That's kind of bizarre. Bug in node?

**Comment by chjj** [comment]
After some more investigate, it looks like when we write unicode to stdout on windows (even when the codepage is 65001, it closes the stdout FD (probably because windows thought it saw an EOF instead of a utf8 series of bytes). @mscdex was right. utf8 is weird on windows. I don't know how to get around this. The windows console still isn't seeing things in unicode.

**Comment by chjj** [comment]
It looks like chcp 65001 causes the windows console to interpret certain unicode characters as EOF and closes stdout, throwing an error.

However, chcp 437 seems to work fine with a lot of unicode characters, including line drawing unicode characters (without using ACS). This is really really weird.

**Comment by chjj** [comment]
This is either a bug in node or cmd.exe (lots of people say they get weird behavior with cp65001). node.js throw on _any_ output while inside blessed if CP is 65001. So, for now, I've allowed cp437 to use unicode because it seems to work in practice.

**Comment by chjj** [comment]
If someone wants to fool around with this and try to figure out why chcp 65001 is broken, that would be amazing. I'm tired out from this.

**Comment by chjj** [comment]
Just an idea. Maybe using utf16 or ucs2 would work better? Something like:

``` js
cp.spawnSync('chcp', ['1200'], { stdio: 'ignore' });
process.stdout.write('\ufeff');
process.stdout.setEncoding('utf16le');
```

**Comment by yaronn** [comment]
Hi @chjj

Sorry for missing the live discussion yesterday.

I cannot use Node 0.11.x hence I don't have execFileSync so the master version still does not work for me. Maybe allow to specify some initialization param in case I would like to override some terminal capabilities I know about out of band?


In addition:

- My windows 7 default code page is 862. There was no need to change it in any stage, only override detectUnicode .
-  Lucia Console is a unicode font but does not support Braille. I had to [force the terminal](http://www.techrepublic.com/blog/windows-and-office/quick-tip-add-fonts-to-the-command-prompt/) to use the [FreeMono](http://www.fonts2u.com/free-monospaced.font) font instead.

**Comment by chjj** [comment]
@yaronn, what happens when you just do `chcp 65001` and force unicode to be enabled?

**Comment by yaronn** [comment]
it still works. setting chcp does not seem to have any affect (at least with the values I tried).

**Comment by chjj** [comment]
Very strange. My windows 7 machine always chokes on any output if the CP is 65001. @mscdex was right. There's very bizarre and unpredictable behavior when it comes to this. I'm not sure what to do other than to just allow unicode for all windows consoles regardless of whether they support unicode.

**Comment by yaronn** [comment]
does it choke even wo the new GetConsoleCP()? That is the only difference between us since in my Node it does not run. 

What will be the implication of always allowing unicode in case of a non-unicode console? Will blessed use unicode characters for some of its rendering or does it only affect user input?

**Comment by chjj** [comment]
@yaronn, also yes. The codepage will probably be different based on the OSes language settings (mine was 437-latin-us, yours is 862-hebrew - of course those correspond to our locations' languages), but it looks like unicode just works for all of them, for the most part. Maybe we could just enable unicode by default and add an ENV variable to disable it if the user wants. `chcp 65001` is just broken. I have no idea why the windows console is such a nightmare.

**Comment by chjj** [comment]
@yaronn, it doesn't choke because of GetConsoleCP - even when I remove that function it chokes just because I called `chcp 65001` beforehand.

**Comment by yaronn** [comment]
@chjj - Also verified that it's not related to the font - switched back to
Lucida and still works ok.

I agree about using unicode by default for windows.

On Mon, Apr 27, 2015 at 2:20 AM, Christopher Jeffrey (JJ) <
notifications@github.com> wrote:

> @yaronn <https://github.com/yaronn>, it doesn't choke because of
> GetConsoleCP - even when I remove that function it chokes just because I
> called chcp 65001 beforehand.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chjj/blessed/issues/130#issuecomment-96447767>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by yaronn** [comment]
Hi @chjj , can you push the master with this change to npm?

**Comment by chjj** [comment]
Published.

**Comment by yaronn** [comment]
Thanks!
