### ISSUE TITLE
server side blessed

### ISSUE THREAD

**Issue by yaronn** [chjj/blessed#157]
I've recently used blessed in a multi-user server side app (https://github.com/yaronn/wopr). I've found two issues:

1. program.global (and other globals) are singletons so will not work with concurrent user sessions. In my case sessions were synchronous so it was not an issue though I did notice blessed to setTimeout in several places and this might have implications.

2. some of the process event registrations leak. for example the following code:

        http.createServer(function (req, res) {
             var program = new blessed.Program()
             setTimeout(function() {res.end(Date.now() + "")}, 0)    
        }).listen(8080);

will claim a lot of memory if this server is called many times (garbage collection will not clean it).
interesting that a client side version of creating program multiple times will not leak.
anyway most events were not relevant on server side (listening to user clicks etc) so I workedaround it with this code which stopped the leak:

    blessed.Program.prototype.listem = function() {}
    process.on = function() {}

**Comment by chjj** [comment]
It's cool you did it with an http server and `curl`. I was thinking more along the lines of tcp and `netcat`/`ncat`/`nc`/`telnet`/`othertcptool` when I removed the `isatty()` check.

One thing you'll have to do to work around the `Screen.global` is when instantating nodes, always add the screen option:

``` js
blessed.box({
  screen: session.screen,
  parent: biggerBox,
  ...
});
```

Otherwise blessed uses the global screen. That's what the `screen` option was originally there for, even though I didn't initiallity plan on having multiple screens, I guess I had the presence of mind to add that option for some reason.

---

`Program.global` shouldn't be an issue since you only really need one program object for the server, and it will only use one. If you need multiple programs for whatever reason, you should do:

```
session.program = blessed.program(...);
session.screen = blessed.screen({
  program: session.program,
  ...
});
```

But I really don't think that part is necessary. The server should only need one global program object for all the screens. Try not doing that first and see if it works.

---

> `blessed.Program.prototype.listem = function() {}`

That's very strange. `listen()` shouldn't leak as long as the socket is destroyed/closed after the session. It just listens for data events on the input and output (in the case of tcp: the socket for both, in the case of http: the req and res, respectively + the socket). If I had to guess, this is because the events are getting bound to it over and over because the socket stays open due to keepalive. We can add a simple check for this just for good measure.

> `process.on = function() {}`

That is most _definitely_ a problem. Blessed is probably binding to the signals/exit/uncaughtException over and over without unbinding them in the construcotrs. We'll include a check for that too.

Or, we could always add a `program.destroy()` and `screen.destroy()` too.

---

I like this. Shouldn't be too much work. I'll get to work on it.

**Comment by chjj** [comment]
@yaronn, the commit above adds .destroy() methods to Program and Screen, and should also prevent memory leaks by keeping track of whats bound to the sockets/ttys/requests/responses and process object.

**Comment by yaronn** [comment]
thanks @chjj for the quick resolution!

I already propogate the screen object for every element. The issue is that screen (and program) globals are singeltons. I can not use a single program object since each user request should be rendered with a different col/row/term combination and of course to a different buffer.

**Comment by chjj** [comment]
@yaronn, I took that into account. The latest commits added a way to keep track of multiple `program` and `screen` objects and `program.destroy()` or `screen.destroy()` them if need be.

**Comment by chjj** [comment]
The commit just above should allow use of the same socket for multiple Programs without binding any extra events (i.e. memory leak).

**Comment by chjj** [comment]
@yaronn, how is it working? Anymore memory leaks?

**Comment by yaronn** [comment]
@chjj - just had a chance to check. no more memory leaks, great work! for anyone else trying this make sure to destroy the screen after res.end('') otherwise the user will see a blank screen.

**Comment by chjj** [comment]
@yaronn, I've made a lot of improvements to server side blessed / multiple screens. I've added docs: https://github.com/chjj/blessed#multiple-screens

And an example telnet server which can serve multiple screens: https://github.com/chjj/blessed/blob/master/example/blessed-telnet.js

**Comment by chjj** [comment]
Also, you no longer have to pass `screen: socket.screen` or whatever it may be. Blessed figures it out for you.

**Comment by yaronn** [comment]
very cool! there are definitely many use cases to server side blessed.
