### ISSUE TITLE
cp437 encoded text becomes garbled in textarea.

### ISSUE THREAD

**Issue by emdeeeks** [chjj/blessed#166]
Hi,

I'm in the process of building an ascii/ansi art editor. I'm currently using iconv-lite to convert a .ans file to cp437, and then placing it in a textarea. Logging the output to the console isn't perfect (I'll contact the author of iconv-lite about that) but appears much better than placing the content in a textarea and rendering via blessed. Am I missing a setting somewhere? 

Output via console;

![2015-08-11-190715_647x974_scrot](https://cloud.githubusercontent.com/assets/3227764/9204283/9f67098a-405c-11e5-9c9a-29b3ac2658a6.png)

Output via blessed;

![2015-08-11-190956_647x974_scrot](https://cloud.githubusercontent.com/assets/3227764/9204295/b0604602-405c-11e5-981e-252d8b34bd6e.png)

The code I'm using to render both is below. I'm just uncommenting out the obvious lines to output via console.

``` JS
process.stdout.write("echo -en '\033]4;0;#000000\007'"); // black
process.stdout.write("echo -en '\033]4;1;#AD0000\007'"); // red
process.stdout.write("echo -en '\033]4;2;#00AA00\007'"); // green
process.stdout.write("echo -en '\033]4;3;#AD5500\007'"); // yellow
process.stdout.write("echo -en '\033]4;4;#0000AD\007'"); // blue
process.stdout.write("echo -en '\033]4;5;#AD00AD\007'"); // magenta
process.stdout.write("echo -en '\033]4;6;#00AAAD\007'"); // cyan
process.stdout.write("echo -en '\033]4;7;#ADAAAD\007'"); // white
process.stdout.write("echo -en '\033]4;8;#525552\007'"); // light-black
process.stdout.write("echo -en '\033]4;9;#FF5255\007'"); // light-red
process.stdout.write("echo -en '\033]4;10;#52FF52\007'"); // light-green
process.stdout.write("echo -en '\033]4;11;#FFFF52\007'"); // light-yellow
process.stdout.write("echo -en '\033]4;12;#5255FF\007'"); // light-blue
process.stdout.write("echo -en '\033]4;13;#FF55FF\007'"); // light-magenta
process.stdout.write("echo -en '\033]4;14;#52FFFF\007'"); // light-cyan
process.stdout.write("echo -en '\033]4;15;#FFFFFF\007'"); // light-white

fs = require('fs');
iconv = require('./include/iconv-lite');
var buf = fs.readFileSync(process.argv[2], { encoding: 'binary' });
var str = iconv.decode(buf, 'cp437');
//console.log(str);
//process.exit(0);

var blessed = require("./include/blessed");
var screen = blessed.screen({
    cursor: {
        artificial: true,
        shape: 'underline',
        blink: false,
        color: null // null for default
    },
});

var canvas = blessed.Textarea({
    scrollable: true,
    alwaysScroll: true,
    top: 0,
    left: 0,
    width: 80,
    height: screen.height,
    tags: true,
    input: true,
    keyable: true,
    keys: true,
    smartCSR: true,
    style: {
        fg: 'white',
        bg: 'black'
    }
});

screen.append(canvas);
screen.render();

canvas.setContent(str);
screen.render();
```

The ansi file I used can be viewed here: http://sixteencolors.net/pack/blocktronics_awaken/we-clutch.ans
and download here: http://sixteencolors.net/pack/blocktronics_awaken/we-clutch.ans/download

Thanks.

**Comment by chjj** [comment]
> `var str = iconv.decode(buf, 'cp437');`

You're converting cp437 to ascii just fine. Codepage 437 doesn't look like the issue here.

In the old days, ANSI art was meant to be displayed in terminals. It's impossible to write it to a regular blessed element without causing layout issues because it needs to move the cursor around dynamically, hence all the ^[[xC's (parm_right_cursor) you see displayed. Blessed doesn't allow those codes, not only because of extra complexity, but just because of the extremely limited amount of use-cases.

The __only__ blessed element that can display older ansi art is the `Terminal` element (term.js needs to be installed). An example is available in my ansi-viewer: https://github.com/chjj/blessed/blob/master/example/ansi-viewer/index.js#L32

If I were you, this is what I'd do:

1. Spin up a headless `Terminal` element with term.js installed (`term = blessed.terminal(...)`).
2. Read an ansi art file.
3. Convert file contents from cp437 to ascii/utf-8.
4. Remove all MCI codes from the text.
5. Reset your terminal element and `term.write(ansi)` the text to it.
6. Take an SGR screenshot of the element using `screenshot = term.screenshot()`.
7. Now you have, at least what I've dubbed, an "SGR screenshot", which is a string containing __only__ SGR sequences (nothing dynamic like cursor movement is necessary). It could theoretically be displayed on a color dumb terminal it's so simple.
8. Take this string and call `box.setContent(screenshot)` on any regular blessed element.
9. Now the user can modify it in the box and then call `screenshot = box.screenshot()` again once you're done.
10. Save the file as an "SGR screenshot" so you don't have to repeat steps 1-7 all over again.
11. Optionally repeat steps 2-11 if old ansi art, or repeat 8-11 with sgr screenshot ansi art.

Once it's saved as an SGR screenshot, it's still considered ANSI art, just slightly larger than other pieces of ANSI art due to the need for more spaces since we don't want to move the cursor. In the days of BBSes they tried to save as much space as the could with cursor movements due to bandwidth limitations. Nowdays, it's better to just only use SGR sequences (a few more bytes doesn't mean as much as it did in the '80s).

You can read about the `screenshot` method more in the docs/readme. ANSI art is the one of the primary reasons the `screenshot()` method exists (but it does have other uses too).

I recommend looking at blessed's ansi art viewer if you want a working example of the above: https://github.com/chjj/blessed/blob/master/example/ansi-viewer/index.js#L153

![ansi-viewer](https://raw.githubusercontent.com/chjj/blessed/master/img/ansi-viewer.png)

I'm looking forward to your ansi art editor. I've wanted one for a while (I was thinking of extending ansi-viewer but haven't gotten around to it). Let me know if you have anymore issues with blessed along the way.
