### ISSUE TITLE
How to render a child element only?

### ISSUE THREAD

**Issue by kjirou** [chjj/blessed#169]
Hi, There is a one question.

I tried to render a child element only, by the following code:

```
var blessed = require('blessed');
var screen = blessed.screen();

screen.key(['escape', 'C-c'], function(ch, key) {
  process.exit(0);
});

var foo = blessed.box({
  parent: screen,
  top: 'top',
  left: 'left',
  width: 12,
  height: 5,
  tags: true,
  style: {
    fg: 'white',
    bg: 'magenta'
  },
  content: 'foo'
});

var bar = blessed.box({
  parent: foo,
  top: 'center',
  left: 'center',
  width: 10,
  height: 1,
  tags: true,
  style: {
    fg: 'white',
    bg: 'black'
  },
  content: 'bar'
});

screen.key('f', function(ch, key) {
  foo.setContent(foo.content + 'x');
  foo.render();
});

screen.key('b', function(ch, key) {
  bar.setContent(bar.content + 'x');
  bar.render();
});

screen.render();
```

I expected this output, when I pressed "b":

![](https://i.gyazo.com/def3d561c3cebe7ec48e868e806b1b94.png)

However, I got this one:

![](https://i.gyazo.com/e5ac0368c9149f1aa31aba67acb53b43.png)

----

After, I found `screen.draw` method.

Always do I need to execute `screen.draw` after the `element.render`?

**Comment by chjj** [comment]
Normally, you'll never have to call `element.render()` or `screen.draw()` (these are generally meant for blessed to use internally). 

_Only_ `screen.render()` is necessary (if you changed something, like content). It handles everything for you.

Always do this instead:

``` js
  bar.setContent(bar.content + 'x');
  screen.render();
```

To answer your question, no, you cannot render a child element without the parent. It's impossible. Blessed assumes your tree structure is the desired rendering order.

You could do a few things in turn though:

- Detach the element from its parent, append it to the parent's parent, and reposition it properly (and then hide() the original parent when you want).
- Create a `Layout` element, which uses a custom renderer, to check something like a `noRenderParent` flag on an element (see the readme for an example of a renderer). It would be a little hacky since you would have to recursively iterate over all children in the renderer (`element.forDescendants()`) and check for the option.
- Remove all content and style from the parent element.
- Create a duplicate element behind the parent which is displayed when the parent is detached.

The last two are probably the ugliest solutions. I would go for the first one.

**Comment by kjirou** [comment]
@chjj Thank you your reply. I understood.

Basically, I am going to use the `screen.draw`.
If speed is not enough, I try taught hacks.

**Comment by chjj** [comment]
@kjirou, don't use screen.draw. Only use `screen.render()`.

**Comment by kjirou** [comment]
@chjj Oh, I'm sorry.. It was typo. 

I learned :muscle: `Only use screen.render()` :muscle:
