### ISSUE TITLE
Make text selectable

### ISSUE THREAD

**Issue by gitnik** [chjj/blessed#263]
I can't find an option to make text inside my box selectable and thus copyable?

**Comment by pt300** [comment]
Uh. What?

**Comment by gitnik** [comment]
The docs don't mention how I can make it so that text inside a box can be selected via mouse.

Here I have a box into which I pipe the output of a gulp process. But as you can see in the gif I have no way of interacting with the text:
http://giphy.com/gifs/3otOKmBidQetuQ6Aww

**Comment by pt300** [comment]
That's not problem with blessed but with your terminal.
Usually you can have problems with selection when output gets updated. To prevent that you could try pausing stdout with ctrl+s, copy what you want and resume it with ctrl+q. That should at least work on Linux.

**Comment by pt300** [comment]
As I think about it now it might be also caused by blessed capturing mouse clicks.
You could try finding a way to disable that.

**Comment by gitnik** [comment]
Ok thanks I will give that a try

**Comment by gitnik** [comment]
`mouse: false` did the trick. thank you!

**Comment by LoganDark** [comment]
on mac you have to hold down `fn` because otherwise Blessed recieves all the mouse clicks

**Comment by tbranyen** [comment]
I found that on Linux (urxvt) you can hold down shift to select text.

**Comment by wearhere** [comment]
I have found that it is not specifically `mouse: false` that will enable text selection, but rather making
sure that `screen.program.enableMouse()` is not called. That method can be called if you use scroll/hover/click handling _anywhere_ in your application, not limited to `mouse: true`, but also `program.on('click')`, the use of a hover style, or even enabling the debug log since that's scrollable.

Rather than try to disable all of those uses of mouse events, you can call `screen.program.disableMouse()` when you want to enable text selection, and then call `screen.program.enableMouse()` again when you want to use hover or click handling.

A really fortunate thing is that calling `disableMouse` not only re-enables native Terminal text selection, but also native scrolling. Let's say you have a `Log` component. By default that `Log` component will not scroll unless you pass `mouse: true` to it. So if you pass `mouse: false` (because you're trying to re-enable text selection), you'll break its scrolling. But then if you call `screen.program.disableMouse()`, you'll _re-enable scrolling_. (And, the scrolling will be at a [much nicer speed](https://github.com/mixmaxhq/custody/issues/37#issuecomment-390855414) than blessed's default scrolling imo.)
